spring.application.name=customer-api

# Database connect setting
pring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/crm_db?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate c
# update: If no data table is present at startup, it will be created automatically for you.
spring.jpa.hibernate.ddl-auto=update
# The console prints the SQL syntax executed behind the scenes.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Setting
# The key must be longer than 32 characters; this key will be used to sign all tokens.
jwt.secret=${JWT_SECRET:ThisIsASuperSecretKeyForCrmBackendApiTutorial2024!}

# ??? Port (??????? PORT)
server.port=${PORT:8080}